version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    container_name: demo-web

  db:
    image: postgres:15
    container_name: demo-db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: testdb
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: